#!/bin/sh
cat <<'ART'

     /search
        ├─ lvl1        (глубина 1)
        │   └─ lvl2    (глубина 2)
        │       └─ lvl3  ← стоп, дальше не идём
        │           ├─  ...
        │
     -maxdepth 3

     * find + -maxdepth — простое, но мощное сочетание. *

ART
