[options]
mode = "Interactive"
fs_analyzer = true
fs_accuracy = 0.7
observe_list = [ "/home/anton/LinuxWork/study/8/nirs/dvs/tmp/file", "/usr/bin/", "/usr/local/bin", "/etc/",]
output_analyzer = true
output_accuracy = 0.7

[changes."/home/anton/LinuxWork/study/8/nirs/dvs/tmp/file"]
path = "/home/anton/LinuxWork/study/8/nirs/dvs/tmp/file"
is_dir = false
pardir = "/home/anton/LinuxWork/study/8/nirs/dvs/tmp"
state = "deleted"
