stage_amount = 1

[stage0.options]
mode = "Interactive"
observe_dirs = [ "/home/anton/LinuxWork/study/8/nirs/", "/usr/bin/", "/usr/local/bin", "/etc/",]
fs_analyzer = true
fs_accuracy = 0.7
output_analyzer = true
output_accuracy = 0.7

[stage0.changes."/home/anton/LinuxWork/study/8/nirs/dvs/tmp/t"]
path = "/home/anton/LinuxWork/study/8/nirs/dvs/tmp/t"
is_dir = false
pardir = "/home/anton/LinuxWork/study/8/nirs/dvs/tmp"
hash = "16825458760271544958"
state = "created"
