[options]
mode = "Interactive"
observe_dirs = [ "/home/anton/LinuxWork/study/8/nirs/", "/usr/bin/", "/usr/local/bin", "/etc/",]
fs_analyzer = true
fs_accuracy = 0.7
output_analyzer = true
output_accuracy = 0.7

[changes."/home/anton/LinuxWork/study/8/nirs/dvs/tmp"]
path = "/home/anton/LinuxWork/study/8/nirs/dvs/tmp"
is_dir = true
pardir = "/home/anton/LinuxWork/study/8/nirs/dvs"
state = "created"

[changes."/home/anton/LinuxWork/study/8/nirs/dvs/tmp/f"]
path = "/home/anton/LinuxWork/study/8/nirs/dvs/tmp/f"
is_dir = false
pardir = "/home/anton/LinuxWork/study/8/nirs/dvs/tmp"
hash = "16825458760271544958"
state = "created"

[changes."/home/anton/LinuxWork/study/8/nirs/dvs/tmp/ff"]
path = "/home/anton/LinuxWork/study/8/nirs/dvs/tmp/ff"
is_dir = false
pardir = "/home/anton/LinuxWork/study/8/nirs/dvs/tmp"
hash = "16825458760271544958"
state = "created"

[changes."/home/anton/LinuxWork/study/8/nirs/.git/index.lock"]
path = "/home/anton/LinuxWork/study/8/nirs/.git/index.lock"
is_dir = false
pardir = "/home/anton/LinuxWork/study/8/nirs/.git"
state = "deleted"
