#!/bin/bash

function make()
{
	workdir=""
	user="root"


	while [[ ! -z "$1" ]]
	do
		case "$1" in
		--dir | -d)
			set -x
			workdir=$(readlink -f $2)
			shift 2
			;;
		--user | -u)
			user="$2"
			shift 2
			;;
		*) shift;
			;;
		esac
	done

	sudo systemd-nspawn -M debian-stable$$ -D lib/base/debian-stable --user $user --overlay="$PWD/lib/base/debian-stable:$workdir:/" #FIXME add other system standart
}

if [[ -z "$1" ]]
then
	echo "help manual"
else
	case "$1" in
	make)
		shift
		make "$@"
		;;
	*) shift;
		;;
	esac
fi
