#!/bin/sh
cat <<'ART'

    /home
      └── student
           └── dir1
                └── dir2
                     └── ...
                          └── cd_to_me
                                 \o/    <-- вот и ты

     * Абсолютные пути покорены. Tab теперь ваш друг. *

ART
