#!/bin/sh
cat <<'ART'

     depth   0    1    2    3    4
             ▓    ▓    ▓    ▒    ░
                            ^
                        только этот слой

     * -mindepth + -maxdepth = снайпер. -name — для тех, кто стреляет очередями. *

ART
