#!/bin/sh
cat <<'ART'

     dir1/                dir2/
      ├─ file1.txt   ─►    ├─ file1.txt
      ├─ file2.txt   ─►    ├─ file2.txt
      └─ file3.txt   ─►    └─ file3.txt

     * Любопытная Варвара скопирована полностью. Нос — тоже. *

ART
