#!/bin/sh
# Shown after the stage passes. ASCII: developer at the keyboard.
cat <<'ART'

           ,--.
          |o_o |     TODO: fix everything
          |:_/ |     ---------------------
         //   \ \    - [x] найти TODO
        (|     | )   - [ ] исправить TODO
       /'\_   _/`\   - [ ] написать новые TODO
       \___)=(___/

     * TODO собраны. Половина работы сделана — та половина, где ничего не надо делать. *

ART
